server:
  port: 8081
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/skel
    username: root
    password: 12331233
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "jj_group"

logging:
  level:
    root: warn